export const SITE_URL = 'https://www.webmotto.com';

/** Artículos por página en desktop (grid 3 col). En móvil/tablet se ajusta en blog.js. */
export const BLOG_PER_PAGE = 9;
export const BLOG_PER_PAGE_SM = 6;
export const BLOG_PER_PAGE_XS = 4;

export const categories = [
  { key: 'all', label: 'Todos' },
  { key: 'seo', label: 'SEO' },
  { key: 'web', label: 'Desarrollo Web' },
  { key: 'ecommerce', label: 'E-commerce' },
  { key: 'diseno', label: 'Diseño UX/UI' },
  { key: 'mobile', label: 'Apps Móviles' },
  { key: 'marketing', label: 'Marketing' },
  { key: 'saas', label: 'SaaS & Startups' },
];

export const posts = [
  {
    slug: 'core-web-vitals-guia-2026',
    title: 'Core Web Vitals 2026: guía práctica para mejorar el SEO técnico',
    metaDescription:
      'Aprende a optimizar LCP, INP y CLS en 2026. Checklist accionable de Core Web Vitals para posicionar mejor y convertir más en tu web.',
    category: 'seo',
    tags: ['Core Web Vitals', 'SEO técnico', 'Rendimiento web', 'PageSpeed'],
    excerpt:
      'LCP, INP y CLS siguen siendo señales de ranking. Esta guía te muestra cómo medirlos, priorizarlos y corregirlos sin reescribir todo el sitio.',
    date: '2026-09-18',
    author: 'Laura Gómez',
    authorRole: 'Especialista SEO técnico',
    readTime: 9,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Dashboard de analítica web con métricas de rendimiento en un portátil',
    content: [
      { type: 'p', text: 'Los Core Web Vitals siguen siendo uno de los grupos de métricas de experiencia que Google usa en la búsqueda. En 2026, con INP consolidado como sustituto de FID, un sitio lento no solo pierde visitas: pierde posiciones en resultados competitivos.' },
      { type: 'h2', text: 'Qué mide cada Core Web Vital' },
      { type: 'ul', items: ['LCP (Largest Contentful Paint): cuánto tarda en pintar el elemento principal visible (hero, titular o imagen grande).', 'INP (Interaction to Next Paint): latencia percibida al interactuar con botones, menús y formularios.', 'CLS (Cumulative Layout Shift): cuánto se mueve el diseño mientras la página carga.'] },
      { type: 'p', text: 'El objetivo de campo (CrUX) suele ser: LCP ≤ 2,5 s, INP ≤ 200 ms y CLS ≤ 0,1 en el 75% de las sesiones. Lab (Lighthouse) orienta; el dato real de usuarios es el que decide el ranking.' },
      { type: 'h2', text: 'Cómo priorizar las correcciones' },
      { type: 'p', text: 'Empieza por el LCP del hero: precarga de la imagen principal, formato AVIF/WebP, CSS crítico inline y elimina render-blocking de terceros. Después ataca el INP: divide JavaScript largo, usa event handlers ligeros y evita tareas de más de 50 ms en el hilo principal. Para el CLS, reserva dimensiones explícitas en imgs/iframes y evita inyectar banners sobre el contenido.' },
      { type: 'h2', text: 'Checklist rápida antes de publicar' },
      { type: 'ul', items: ['Imagen hero con width/height y prioridad de carga.', 'Fuentes con font-display: swap y preload selectivo.', 'Sin scripts de terceros no esenciales en el head.', 'Layout con aspect-ratio en grid y cards.', 'Medir en Search Console → Rendimiento → Core Web Vitals.'] },
      { type: 'p', text: 'Si tu web ya tiene buen contenido pero no crece en tráfico orgánico, revisa primero las métricas de campo: suelen ser el cuello de botella invisible.' },
    ],
  },
  {
    slug: 'cuanto-cuesta-hacer-una-pagina-web',
    title: '¿Cuánto cuesta hacer una página web? Precios reales 2026',
    metaDescription:
      'Desglose de costos de páginas web en 2026: landing, corporativa, WordPress y e-commerce. Factores que suben o bajan el precio y cómo evitar sobrecostos.',
    category: 'web',
    tags: ['Costos web', 'Presupuesto', 'Landing page', 'Contratar agencia'],
    excerpt:
      'El precio de una web no es un misterio. Te mostramos rangos realistas por tipo de proyecto y qué incluir para no pagar de más.',
    date: '2026-09-15',
    author: 'Carlos Mendoza',
    authorRole: 'Director de proyectos',
    readTime: 8,
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Calculadora y documentos financieros sobre un escritorio',
    content: [
      { type: 'p', text: 'La pregunta “¿cuánto cuesta una página web?” tiene tantas respuestas como tipos de negocio. Aun así, en 2026 los rangos del mercado hispano se mueven en bandas claras si desglosas alcance, diseño y soporte.' },
      { type: 'h2', text: 'Rangos típicos por tipo de sitio' },
      { type: 'ul', items: ['Landing page de campaña: USD 500 – 1.500 (una página, copy orientado a conversión).', 'Web corporativa (5–10 páginas): USD 1.500 – 4.000.', 'WordPress a medida con blog y SEO on-page: USD 2.500 – 6.000.', 'E-commerce catálogo pequeño: USD 3.000 – 8.000.', 'Plataforma SaaS o app web compleja: desde USD 8.000 según módulos.'] },
      { type: 'h2', text: 'Qué hace subir el precio' },
      { type: 'p', text: 'Integraciones de pago, multiidioma, áreas de usuario, migraciones de contenido, diseño original en Figma y requisitos de accesibilidad o rendimiento estrictos agregan horas reales. También suma el copywriting profesional y la fotografía de producto.' },
      { type: 'h2', text: 'Cómo no pagar de más' },
      { type: 'ul', items: ['Define 3 objetivos de negocio medibles antes de pedir cotización.', 'Prioriza páginas críticas en la fase 1 y deja blogs/calculator para fases.', 'Pide desglose por partidas (diseño, desarrollo, SEO, soporte).', 'Verifica que el hosting, dominio y SSL estén incluidos o al menos listados.', 'Exige propiedad del código y accesos al final del proyecto.'] },
      { type: 'p', text: 'Un cotizador transparente —como el que tienes en esta web— te da un piso realista en minutos. Después compara manzanas con manzanes: alcance, plazos y garantía, no solo el número final.' },
    ],
  },
  {
    slug: 'diseno-ux-que-convierte',
    title: 'Diseño UX que convierte: 7 patrones probados para tu web',
    metaDescription:
      'Siete patrones de UX aplicados a sitios de negocios: jerarquía visual, formularios cortos, prueba social y microcopy que aumenta conversiones.',
    category: 'diseno',
    tags: ['UX', 'Conversión', 'Diseño web', 'CRO'],
    excerpt:
      'No basta con que tu web “se vea bonita”. Estos patrones de usabilidad y microcopy mejoran la tasa de conversión sin rediseño total.',
    date: '2026-09-12',
    author: 'María Fernanda Ruiz',
    authorRole: 'Diseñadora de producto',
    readTime: 7,
    image: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Bocetos de wireframes y prototipos de interfaz en papel',
    content: [
      { type: 'p', text: 'El diseño UX no es decoración: es la disciplina que reduce fricción entre la intención del usuario y la acción que tu negocio necesita. Estos siete patrones funcionan en landings, corporativas y e-commerce.' },
      { type: 'h2', text: '1. Jerarquía en Z con un solo CTA dominante' },
      { type: 'p', text: 'Una sola acción principal por viewport. Los secundarios (ghost o outline) no compiten en color de marca.' },
      { type: 'h2', text: '2. Formularios con el mínimo viable' },
      { type: 'p', text: 'Cada campo extra reduce la tasa de envío. Para cotizaciones iniciales: nombre, email, tipo de proyecto y mensaje. El resto se recoge en la llamada de calificación.' },
      { type: 'h2', text: '3. Prueba social cerca del punto de duda' },
      { type: 'ul', items: ['Logos de clientes bajo el hero o junto al CTA.', 'Testimonios con nombre, rol y resultado concreto.', 'Casos con métricas antes/después en portafolio.'] },
      { type: 'h2', text: '4. Microcopy que responde “¿qué pasa si…?”' },
      { type: 'p', text: 'Bajo el botón: “Respuesta en menos de 24 h · Sin compromiso”. En pagos: “Cancela cuando quieras”. Elimina la incertidumbre en el momento exacto de la decisión.' },
      { type: 'h2', text: '5–7. Velocidad, estados vacíos y affordance clara' },
      { type: 'ul', items: ['Objetivo LCP bajo 2,5 s: el diseño también es rendimiento.', 'Estados vacíos con siguiente paso (no un “sin resultados” a secas).', 'Botones que parecen botones: elevación, hover y foco visible.'] },
      { type: 'p', text: 'Implementa los cambios en orden de impacto/effort. Muchas webs ganan +15–30% de leads solo con formularios más cortos y prueba social bien ubicada.' },
    ],
  },
  {
    slug: 'woocommerce-vs-shopify',
    title: 'WooCommerce vs Shopify 2026: cuál elegir para tu tienda',
    metaDescription:
      'Comparativa WooCommerce vs Shopify: costos, personalización, SEO, plugins y soporte. Tabla clara para elegir la plataforma de e-commerce ideal.',
    category: 'ecommerce',
    tags: ['WooCommerce', 'Shopify', 'E-commerce', 'Plataformas'],
    excerpt:
      'Flexibilidad total frente a todo en uno gestionado. Analizamos costos reales, SEO, escalabilidad y cuándo conviene cada opción.',
    date: '2026-09-10',
    author: 'Diego Herrera',
    authorRole: 'Lead e-commerce',
    readTime: 10,
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Paquete de producto listo para envío junto a un portátil con tienda online',
    content: [
      { type: 'p', text: 'WooCommerce y Shopify dominan el e-commerce en español. Ninguno es “el mejor” en abstracto: dependen de tu catálogo, equipo y apetito por el mantenimiento.' },
      { type: 'h2', text: 'Tabla resumen' },
      { type: 'ul', items: ['Hosting y base: WooCommerce (plugin gratuito sobre WordPress) vs Shopify (plan mensual desde ~USD 39 + comisiones).', 'Personalización: WooCommerce gana por código abierto; Shopify por apps y theme system.', 'SEO técnico: ambos muy capaces; Woo permite control granular de URLs y schema; Shopify ha mejorado mucho su arquitectura.', 'Mantenimiento: Shopify incluye hosting, updates y seguridad; Woo requiere equipo o proveedor de soporte.'] },
      { type: 'h2', text: 'Cuándo elegir WooCommerce' },
      { type: 'p', text: 'Cuando ya inviertes en WordPress, necesitas lógica de negocio a medida, catálogo con contenido editorial fuerte o quieres control total de costos de infraestructura a escala.' },
      { type: 'h2', text: 'Cuándo elegir Shopify' },
      { type: 'p', text: 'Cuando priorizas time-to-market, pagos y envíos listos, apps certificadas y un equipo pequeño que no quiere apagar incendios de hosting.' },
      { type: 'h2', text: 'Costo real a 12 meses' },
      { type: 'p', text: 'Suma plan, dominio, temas, apps, pasarela y horas de mantenimiento. En proyectos medianos, la diferencia de sticker price se achica cuando Woo incluye desarrollo a medida que Shopify solo haría con apps de pago.' },
      { type: 'p', text: 'Nuestra recomendación: define catálogo, integraciones (ERP, envíos, CRM) y quién mantiene la tienda. Con esos tres datos, la elección se vuelve evidente.' },
    ],
  },
  {
    slug: 'react-native-vs-flutter-2026',
    title: 'React Native vs Flutter en 2026: rendimiento y costos',
    metaDescription:
      'React Native o Flutter para tu app móvil: rendimiento, UI, ecosistema, tiendas y costo de desarrollo comparado con ejemplos reales.',
    category: 'mobile',
    tags: ['React Native', 'Flutter', 'Apps móviles', 'Desarrollo móvil'],
    excerpt:
      'Dos frameworks multiplataforma consolidados. Comparamos rendimiento nativo, hot reload, hiring y cuándo cada uno brilla.',
    date: '2026-09-08',
    author: 'Andrés Ponce',
    authorRole: 'Tech lead móvil',
    readTime: 9,
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Desarrollador probando una aplicación móvil en un teléfono inteligente',
    content: [
      { type: 'p', text: 'React Native y Flutter compiten por el mismo presupuesto: una base de código para iOS y Android. En 2026 ambos están listos para producción; la diferencia está en el equipo y el tipo de UI.' },
      { type: 'h2', text: 'Rendimiento' },
      { type: 'p', text: 'Flutter renderiza con su propio motor (Skia/Impeller), lo que da consistencia pixel a pixel. React Native con el nuevo arquitectura (JSI, Fabric, TurboModules) reduce puentes y ya no se queda atrás en listas complejas si optimizas bien.' },
      { type: 'h2', text: 'UI y consistencia' },
      { type: 'ul', items: ['Flutter: control total del diseño; ideal si tu marca se aleja del look Material/Cupertino estándar.', 'React Native: se beneficia de componentes nativos (teclado, sheets) y familiaridad web si tu equipo viene de React.'] },
      { type: 'h2', text: 'Ecosistema y hiring' },
      { type: 'p', text: 'React comparte paradigma con la web (hooks, estado), lo que facilita equipos full JS/TS. Flutter con Dart es más nicho pero muy productivo una vez dominado. Ambos publican a App Store y Google Play sin duplicar lógica de negocio.' },
      { type: 'h2', text: 'Costo y time-to-market' },
      { type: 'p', text: 'Un MVP multiplataforma suele costar 30–50% menos que dos apps nativas separadas. Flutter destaca si necesitas animaciones densas o una UI muy custom desde el día uno; React Native si ya tienes API REST, componentes web compartidos o integración profunda con ecosistemas JS.' },
      { type: 'p', text: 'Regla práctica: elige por el talento que puedes contratar y por la sensibilidad visual del producto, no por el hype del framework.' },
    ],
  },
  {
    slug: 'seo-local-negocios-2026',
    title: 'SEO local 2026: cómo aparecer en el mapa de Google',
    metaDescription:
      'Guía de SEO local: Google Business Profile, reseñas, NAP, contenido por zona y señales on-page para posicionar tu negocio en la búsqueda local.',
    category: 'seo',
    tags: ['SEO local', 'Google Business Profile', 'Reseñas', 'Posicionamiento local'],
    excerpt:
      'Si tu negocio depende de la ciudad o el barrio, el SEO local es el canal con mejor retorno. Claves de ficha, reseñas y landing por zona.',
    date: '2026-09-05',
    author: 'Laura Gómez',
    authorRole: 'Especialista SEO técnico',
    readTime: 8,
    image: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Mapa urbano impreso con marcadores de ubicación',
    content: [
      { type: 'p', text: 'El paquete local (mapa + 3 resultados) concentra clics de alta intención: “cerca de mí”, “abierto ahora”, “mejor X en mi ciudad”. Sin SEO local, compites solo en orgánico genérico.' },
      { type: 'h2', text: 'Google Business Profile impecable' },
      { type: 'ul', items: ['Categoría primaria exacta (no inventes).', 'Horario real, fotos recientes y productos/servicios completados.', 'Descripción con palabras clave naturales y CTA.', 'Publicaciones semanales (ofertas, novedades) alimentan la ficha.'] },
      { type: 'h2', text: 'Reseñas que suman confianza' },
      { type: 'p', text: 'Pide reseñas con flujo simple (link directo), responde a todas — también a las malas — con profesionalismo y usa palabras clave del servicio en la respuesta sin sonar a plantilla robótica.' },
      { type: 'h2', text: 'Coherencia NAP y landing por zona' },
      { type: 'p', text: 'Nombre, dirección y teléfono idénticos en web, ficha y directorios. Si atiendes varias ciudades, crea landings útiles (casos, precios, mapas), no textos duplicados con solo cambiar el nombre de la ciudad.' },
      { type: 'h2', text: 'Datos estructurados locales' },
      { type: 'ul', items: ['LocalBusiness con geo, horario y sameAs.', 'FAQ schema en la landing de contacto.', 'Imágenes optimizadas con alt descriptivo del lugar.'] },
      { type: 'p', text: 'Mide en Business Profile Insights: búsquedas de marca vs descubrimiento, clics a llamar y solicitudes de ruta. Ahí verás si el SEO local está trayendo clientes, no solo visitas.' },
    ],
  },
  {
    slug: 'migrar-wordpress-headless',
    title: 'Migrar WordPress a headless: cuándo vale la pena',
    metaDescription:
      'Ventajas y riesgos de una arquitectura headless con WordPress. Checklist de migración, SEO, edición y costos de mantenimiento.',
    category: 'web',
    tags: ['Headless', 'WordPress', 'Jamstack', 'Arquitectura web'],
    excerpt:
      'Decapitar WordPress no es moda: es una decisión de rendimiento y experiencia de edición. Te contamos cuándo conviene y cómo migrar sin perder SEO.',
    date: '2026-09-03',
    author: 'Diego Herrera',
    authorRole: 'Arquitecto de soluciones',
    readTime: 9,
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Código de programación en pantalla de computadora',
    content: [
      { type: 'p', text: 'Headless con WordPress significa usar el CMS clásico como backend de contenido y consumirlo vía REST API o GraphQL desde un frontend moderno (Next, Nuxt, Astro…).' },
      { type: 'h2', text: 'Cuándo tiene sentido' },
      { type: 'ul', items: ['Necesitas frontends múviles (web + app + kiosco) sobre el mismo contenido.', 'El rendimiento del tema clásico ya no llega a buenos Core Web Vitals.', 'Tu equipo de producto quiere despliegues independientes del CMS.', 'Diseño altamente custom que pelea con PHP de plantillas.'] },
      { type: 'h2', text: 'Cuándo NO migrar' },
      { type: 'p', text: 'Si el sitio está estable, el tráfico depende de plugins de membership/e-commerce acoplados y no hay equipo frontend, el costo de headless supera el beneficio. WordPress monolítico bien optimizado sigue ganando a headless mal montado.' },
      { type: 'h2', text: 'Checklist de migración sin perder SEO' },
      { type: 'ul', items: ['Inventario de URLs y redirecciones 301.', 'Preservar slugs, fechas canónicas y schema Article.', 'SSG o SSR para HTML inicial con contenido real.', 'Migrar imágenes a CDN y mantener rutas o redirects.', 'Validar Search Console después del cutover.', 'Formación al equipo editor: cómo publicar en el nuevo flujo.'] },
      { type: 'h2', text: 'Costo de mantenimiento' },
      { type: 'p', text: 'Suma hosting del frontend, cache/CDN y coordinación de versiones CMS↔front. Compensa cuando el frontend cambia a menudo y el contenido cambia a otro ritmo.' },
      { type: 'p', text: 'Conclusión: headless es un acelerador de producto, no un trofeo de arquitectura. Migra por dolor concreto, no por tendencia.' },
    ],
  },
  {
    slug: 'email-que-vende-b2b',
    title: 'Email marketing B2B que vende sin sonar a spam',
    metaDescription:
      'Estructura de campañas B2B: segmentación, asunto, secuencias de nurturing y métricas que importan. Plantillas de email que abren y cierran.',
    category: 'marketing',
    tags: ['Email marketing', 'B2B', 'Automatización', 'Leads'],
    excerpt:
      'El email sigue siendo el canal con mejor ROI en B2B. Cómo segmentar, escribir asuntos honestos y construir secuencias que nutren hasta la cita.',
    date: '2026-09-01',
    author: 'Sofía Ramírez',
    authorRole: 'Growth marketer',
    readTime: 7,
    image: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Buzón de correo electrónico con mensajes nuevos en un portátil',
    content: [
      { type: 'p', text: 'En B2B el email no muere: se filtra. Quien llega a la bandeja con mensaje útil y timing correcto convierte mejor que en redes, donde el algoritmo es el intermediario.' },
      { type: 'h2', text: 'Segmenta antes de escribir' },
      { type: 'ul', items: ['Por etapa: frío (educación), tibio (casos), caliente (cota).', 'Por rol: dueño, marketing, TI.', 'Por comportamiento: abrió pricing, descargó guía, visitó /cotizador.'] },
      { type: 'h2', text: 'Asunto honesto y previsualización con gancho' },
      { type: 'p', text: 'Nada de “¡ÚLTIMO AVISO!”. Prueba: asunto con un dato concreto + preview que completa la promesa. 30–45 caracteres de asunto suelen rendir mejor en móvil.' },
      { type: 'h2', text: 'Secuencia mínima viable (5 emails)' },
      { type: 'ul', items: ['1. Bienvenida + único recurso valioso.', '2. Problema común + framework para resolverlo.', '3. Caso con métrica real.', '4. Objeciones (precio, tiempo, garantía) con respuestas.', '5. CTA directo a llamada o cotizador con franjas horarias.'] },
      { type: 'h2', text: 'Métricas que importan' },
      { type: 'p', text: 'Olvidopens% vanity si el panel está sucio. Prioriza reply rate, reuniones agendadas y leads calificados. Limpia bounces y da de baja inactivos a 90 días: la reputación del dominio lo agradece.' },
      { type: 'p', text: 'Un buen email B2B se lee como un consultor útil, no como un folleto. Escribe una idea por envío y cierra con un solo pedido.' },
    ],
  },
  {
    slug: 'pricing-saas-que-no-espante',
    title: 'Cómo diseñar pricing de SaaS que no espante al usuario',
    metaDescription:
      'Estrategias de precios SaaS: value-based, tiers, free trial vs freemium y errores comunes. Ejemplos de empaquetado que aumentan MRR.',
    category: 'saas',
    tags: ['SaaS', 'Pricing', 'Monetización', 'Estrategia de producto'],
    excerpt:
      'El precio es parte del producto. Cómo elegir tiers, anclas de valor y trial sin regalar el servicio ni asustar al comprador.',
    date: '2026-08-28',
    author: 'Carlos Mendoza',
    authorRole: 'Director de proyectos',
    readTime: 8,
    image: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Gráficos financieros y planificación de precios en documentos',
    content: [
      { type: 'p', text: 'El pricing de SaaS no se adivina en una reunión de dos horas: se diseña con valor percibido, costos de servicio y lo que aguanta tu mercado sin bajar la marca.' },
      { type: 'h2', text: 'Value-based vs cost-plus' },
      { type: 'p', text: 'Cost-plus solo cubre hosting y horas. Value-based pregunta: ¿cuánto ahorra o gana el cliente al mes con el resultado? Ancla el precio a ese valor con margen sanó.' },
      { type: 'h2', text: 'Tiers que guían, no confunden' },
      { type: 'ul', items: ['3 planes suelen bastar (Starter, Pro, Business).', 'El plan del medio es el ancla: marca el “más popular”.', 'Diferencia por capacidad o valor (asientos, volumen, automatizaciones), no por quitar features básicas de forma arbitraria.', 'Enterprise con “Hablar con ventas” para deals con compliance.'] },
      { type: 'h2', text: 'Trial o freemium' },
      { type: 'p', text: 'Trial (14 días) si el valor se percibe rápido y necesitas emails de onboarding intensivos. Freemium si el producto se expande viralmente (invitar equipo, compartir links). Freemium mal acotado se convierte en soporte gratis para siempre.' },
      { type: 'h2', text: 'Errores que matan el MRR' },
      { type: 'ul', items: ['Demasiados add-ons al checkout.', 'Descuentos anuales agresivos sin entender CAC.', 'Cambios de precio sin aviso ni grandfathering.', 'Ocultar precios cuando tu ICP espera transparencia.'] },
      { type: 'p', text: 'Revisa pricing cada 6–12 meses con datos de activación, churn y expansion. El precio incorrecto no solo cuesta dinero: segmenta mal a tus clientes.' },
    ],
  },
  {
    slug: 'auditoria-seo-en-30-dias',
    title: 'Auditoría SEO en 30 días: plan semana a semana',
    metaDescription:
      'Plan de auditoría SEO de un mes: rastreo, indexación, contenido, enlaces y CWV. Checklist semanal para equipos de marketing y devs.',
    category: 'seo',
    tags: ['Auditoría SEO', 'Checklist', 'SEO on-page', 'Técnico'],
    excerpt:
      'Un calendario realista de 4 semanas para detectar y priorizar todo lo que frena tu orgánico: de crawl budget a content gaps.',
    date: '2026-08-25',
    author: 'Laura Gómez',
    authorRole: 'Especialista SEO técnico',
    readTime: 11,
    image: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Análisis de datos y gráficos de rendimiento de un sitio web',
    content: [
      { type: 'p', text: 'Una auditoría sin fechas se queda en un PDF que nadie ejecuta. Este plan de 30 días distribuye el trabajo entre SEO, contenido y desarrollo con entregables claros.' },
      { type: 'h2', text: 'Semana 1 — Rastreo e indexación' },
      { type: 'ul', items: ['Crawl completo (Screaming Frog / Sitebulb / consola).', 'Robots, sitemap vivo y códigos 4xx/5xx.', 'Directivas noindex accidental en plantillas clave.', 'HTTPS, canonicals y parámetros de URL.', 'Entregable: lista priorizada de errores bloqueantes.'] },
      { type: 'h2', text: 'Semana 2 — Index on-page y arquitectura' },
      { type: 'ul', items: ['Title y meta description únicos en top 50 URLs.', 'Jerarquía H1/H2 y enlazado interno a money pages.', 'Schema (Organization, Article, Product, FAQ).', 'Imágenes: alt, peso y lazy correcto.', 'Entregable: matriz URL ↔ keyword ↔ intención.'] },
      { type: 'h2', text: 'Semana 3 — Contenido y Core Web Vitals' },
      { type: 'ul', items: ['Content gaps vs competidores.', 'Fusionar o redirigir canibalizaciones.', 'LCP/INP/CLS en páginas de mayor tráfico.', 'Entregable: backlog dev + briefs de contenido.'] },
      { type: 'h2', text: 'Semana 4 — Autoridad, local y reporte' },
      { type: 'ul', items: ['Enlaces rotos y oportunidades de guest/citas.', 'Si aplica: fichas locales y reseñas.', 'Baseline en Search Console y GA4.', 'Entregable: roadmap 90 días con impacto estimado.'] },
      { type: 'p', text: 'Cierra la auditoría con una reunión de priorización: impacto × esfuerzo. Lo que no entra al sprint, no existe.' },
    ],
  },
  {
    slug: 'checkout-que-convierte',
    title: 'Checkout de e-commerce que convierte: 12 mejoras',
    metaDescription:
      'Reduce abandono de carrito con estos 12 cambios en tu checkout: guest checkout, costos claros, confianza y optimización móvil.',
    category: 'ecommerce',
    tags: ['Checkout', 'CRO', 'Carrito', 'Conversión e-commerce'],
    excerpt:
      'El abandono de carrito ronda el 70%. Estas mejoras de UX, confianza y precios transparentes recuperan ventas sin tocar el catálogo.',
    date: '2026-08-22',
    author: 'Diego Herrera',
    authorRole: 'Lead e-commerce',
    readTime: 8,
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Tarjeta de crédito y compra en línea desde un portátil',
    content: [
      { type: 'p', text: 'Cada fricción en el checkout cuesta dinero. Antes de rediseñar todo, aplica estas mejoras de alto impacto y mide con A/B o al menos con embudo pre/post.' },
      { type: 'h2', text: 'Precio y transparencia' },
      { type: 'ul', items: ['Impuestos y envío estimados temprano (no solo en el último paso).', 'Código de cupón en un acordeón, no como campo obligatorio mental.', 'Ahorro visible al comprar el plan o bundle anual si aplica.'] },
      { type: 'h2', text: 'Formulario minimalista' },
      { type: 'ul', items: ['Guest checkout siempre.', 'Autocompletar y inputmode numérico en teléfono/tarjeta.', 'Errores inline junto al campo, no en un banner arriba.', 'Una columna en móvil; resumen sticky.'] },
      { type: 'h2', text: 'Confianza en el momento exacto' },
      { type: 'ul', items: ['Sello de pago y cifrado cerca del botón final.', 'Política de devolución en enlace corto.', 'Testimonios o “+2.400 pedidos” sin gritar.'] },
      { type: 'h2', text: 'Rendimiento y recovery' },
      { type: 'p', text: 'Checkout lento en 4G pierde móviles. Además: email de carrito a 1h y 24h, y remarketing con el producto exacto abandonado.' },
      { type: 'p', text: 'Prioriza guest checkout + costos claros: suelen ser el 40% del beneficio de una ronda de optimización.' },
    ],
  },
  {
    slug: 'dark-mode-o-light-mode',
    title: 'Dark mode o light mode: qué conviene a tu marca',
    metaDescription:
      'Dark vs light en interfaces: legibilidad, accesibilidad, preferencia de usuario y marca. Cómo decidir y testear el modo visual de tu producto.',
    category: 'diseno',
    tags: ['Dark mode', 'Accesibilidad', 'Design system', 'UI'],
    excerpt:
      'No es solo estética: contraste, fatiga ocular y percepción de marca. Cómo elegir modo por defecto y ofrecer toggle sin romper el sistema de diseño.',
    date: '2026-08-20',
    author: 'María Fernanda Ruiz',
    authorRole: 'Diseñadora de producto',
    readTime: 6,
    image: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Interfaz de aplicación móvil en modo oscuro sobre un teléfono',
    content: [
      { type: 'p', text: 'Dark mode dejó de ser feature de early adopters: los sistemas operativos lo exigen y parte de tu audiencia lo tiene activo. La pregunta ya no es “si”, sino “cómo”.' },
      { type: 'h2', text: 'Ventajas de cada modo' },
      { type: 'ul', items: ['Light: mejor lectura larga en entornos luminosos, sensación de “documento/profesional”, fotos de producto se ven más fiel.', 'Dark: menor fatiga en baja luz, ahorro en OLED, estética premium para dashboards y dev tools.'] },
      { type: 'h2', text: 'Accesibilidad real' },
      { type: 'p', text: 'En dark, evita gris puro #FFF a full: usa off-white. En ambos modos, contraste WCAG AA (4.5:1 en texto normal). Los estados de error y éxito necesitan tokens propios por modo, no solo invertir hue.' },
      { type: 'h2', text: 'Recomendación de producto' },
      { type: 'ul', items: ['Sitio marketing B2B serio: light por defecto + respeta prefers-color-scheme si lo implementas completo.', 'Dashboard / app de uso prolongado: dark por defecto o toggle con persistencia.', 'Nunca mitades del sistema en un modo y mitades en el otro.'] },
      { type: 'p', text: 'Si ofreces toggle, guárdalo en localStorage y sincroniza con el sistema en el primer load para evitar flash del tema incorrecto.' },
    ],
  },
  {
    slug: 'push-notifications-que-no-odian',
    title: 'Push notifications que no odian: frecuencia y copy',
    metaDescription:
      'Estrategia de push notifications para apps: segmentación, timing, deep links y opt-out inteligente para subir retención sin frustrar.',
    category: 'mobile',
    tags: ['Push notifications', 'Retención', 'UX móvil', 'Engagement'],
    excerpt:
      'Un push malo borra la app. Cómo segmentar por comportamiento, escribir notificaciones útiles y medir retención en lugar de vanity opens.',
    date: '2026-08-18',
    author: 'Andrés Ponce',
    authorRole: 'Tech lead móvil',
    readTime: 7,
    image: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Notificaciones push en la pantalla de un smartphone',
    content: [
      { type: 'p', text: 'Las push notifications son permiso temporal. Si lo malgastas, el usuario desactiva y rara vez vuelve a activar. Trátalas como un canal de producto, no de spam masivo.' },
      { type: 'h2', text: 'Segmenta por evento, no por “todos”' },
      { type: 'ul', items: ['Transaccional: estado de pedido, pago, check-in (esperado y de alta utilidad).', 'Reengagement: carrusel abandonado, trial por vencer.', 'Contenido: solo si el usuario lo pidió y con cadencia acordada.'] },
      { type: 'h2', text: 'Copy de una línea con utilidad' },
      { type: 'p', text: '¿Qué hace el usuario al leer esto en 2 segundos? “Tu pedido #1842 sale hoy 🚚 · Ver tracking” gana a “¡No te lo pierdas!”. Evita clickbait: la notificación debe cumplir lo que promete al abrir.' },
      { type: 'h2', text: 'Timing y quiet hours' },
      { type: 'p', text: 'Respeta zona horaria y horas de sueño. En B2B evita domingos; en consumo prueba ventanas distintas y mide por cohorte, no por open global.' },
      { type: 'h2', text: 'Deep link y medición' },
      { type: 'ul', items: ['Abre la pantalla exacta, nunca el home genérico.', 'UTM o atribución interna por campaña.', 'Métrica madre: retención D7/D30 y acciones completadas, no solo open rate.', 'Opt-out inteligente: permite reducir frecuencia antes de desactivar todo.'] },
      { type: 'p', text: 'Regla de oro: si no la enviarías a tu propio teléfono un domingo a las 23:00, no la envíes.' },
    ],
  },
  {
    slug: 'migracion-http2-http3-seo',
    title: 'HTTP/2 y HTTP/3: impacto real en SEO y UX',
    metaDescription:
      'Qué aportan HTTP/2 y HTTP/3 a la velocidad percibida, cómo habilitarlas y qué medir. Relación real entre protocolos, Core Web Vitals y ranking.',
    category: 'web',
    tags: ['HTTP/3', 'Rendimiento', 'SEO técnico', 'Hosting'],
    excerpt:
      'El protocolo no aparece en los informes de Lighthouse, pero acelera carga real. Guía para activarlo y comprobar el beneficio en el navegador.',
    date: '2026-08-15',
    author: 'Diego Herrera',
    authorRole: 'Arquitecto de soluciones',
    readTime: 6,
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Servidores de red en un centro de datos',
    content: [
      { type: 'p', text: 'HTTP multiplexeó la web con HTTP/2; HTTP/3 (QUIC) reduce la latencia de handshake y mejora redes inestables. El SEO no rankea “por protocolo”, pero sí por la experiencia que este mejora.' },
      { type: 'h2', text: 'Ganancias concretas' },
      { type: 'ul', items: ['Menor head-of-line blocking en conexiones perdidas (móvil 4G/5G imperfecto).', 'Handshake más rápido al integrar TLS 0-RTT en ciertos escenarios.', 'Mejor comportamiento con cambios de red (Wi-Fi ↔ datos).'] },
      { type: 'h2', text: 'Cómo saber si está activo' },
      { type: 'p', text: 'En Chrome: DevTools → Network → Protocol (h3, h2, http/1.1). O `chrome://net-export` o cabeceras del servidor. Cloudflare y muchos CDNs activan HTTP/3 con un toggle.' },
      { type: 'h2', text: 'Qué medir después de activarlo' },
      { type: 'ul', items: ['LCP de campo en mobile (CrUX o RUM).', 'Tasa de rebote y tiempo en landing de campañas.', 'INP en páginas con muchos scripts (el protocolo ayuda, pero el JS manda).'] },
      { type: 'p', text: 'Si tu hosting no soporta HTTP/3, no es blocker: optimiza assets y JS primero. El protocolo es el coche; tu frontend es el motor.' },
    ],
  },
  {
    slug: 'brief-efectivo-para-tu-agencia',
    title: 'Cómo escribir un brief efectivo para tu agencia web',
    metaDescription:
      'Plantilla de brief de proyecto web: objetivos, audiencia, referencias, alcance y criterios de éxito para recibir una cotización precisa.',
    category: 'marketing',
    tags: ['Brief', 'Agencia web', 'Gestión de proyectos', 'Presupuesto'],
    excerpt:
      'Un buen brief reduce correcciones y presupuestos inflados. Incluye estos 10 puntos y recibe propuestas comparables entre sí.',
    date: '2026-08-12',
    author: 'Sofía Ramírez',
    authorRole: 'Growth marketer',
    readTime: 6,
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Persona tomando notas en un cuaderno junto a un portátil',
    content: [
      { type: 'p', text: 'Las cotizaciones vagas producen propuestas vagas. Con 30 minutos de brief bien estructurado, tu agencia puede dar precio y plazo con menos huecos y menos “de cuál hablamos”.' },
      { type: 'h2', text: 'Los 10 puntos del brief' },
      { type: 'ul', items: ['1. Objetivo de negocio en una frase (leads, ventas, reclutamiento…).', '2. Audiencia primaria y secundaria.', '3. Oferta principal y precio/rango si es público.', '4. Páginas o módulos necesarios (lista).', '5. Integraciones: pagos, CRM, ERP, analytics.', '6. Contenido disponible (textos, fotos, casos).', '7. Referencias de estilo — y qué NO te gusta.', '8. Plazo duro (evento, campaña, temporada).', '9. Presupuesto o rango aprobado.', '10. Criterios de éxito medibles a 90 días.'] },
      { type: 'h2', text: 'Errores comunes' },
      { type: 'ul', items: ['“Quiero algo moderno como Apple” sin definir restricciones.', 'Ocultar el presupuesto y luego rechazar rangos razonables.', 'Pedir 8 features en la fase 1 sin priorizar.'] },
      { type: 'p', text: 'Adjunta el brief a la solicitud de cotización (o llénalo en el formulario de la agencia). Notarás la diferencia en la calidad de la primera propuesta.' },
    ],
  },
  {
    slug: 'arquitectura-informacional-sitios',
    title: 'Arquitectura informacional: estructura que rankea',
    metaDescription:
      'Cómo organizar menús, silos y enlazado interno para SEO y usabilidad. Reglas de arquitectura informacional en sitios de servicios y e-commerce.',
    category: 'seo',
    tags: ['Arquitectura web', 'Enlazado interno', 'UX', 'SEO on-page'],
    excerpt:
      'Google y tus usuarios navegan la misma estructura. Silos claros, menús predecibles y enlaces contextuales que distribuyen autoridad.',
    date: '2026-08-10',
    author: 'Laura Gómez',
    authorRole: 'Especialista SEO técnico',
    readTime: 8,
    image: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Estanterías de biblioteca organizadas como metáfora de arquitectura de contenido',
    content: [
      { type: 'p', text: 'La arquitectura informacional decide qué tan fácil es encontrar y rankear tu contenido. Un blog sin silos y un menú de 20 items rotos diluyen autoridad y confunden.' },
      { type: 'h2', text: 'Principios base' },
      { type: 'ul', items: ['Tema principal → sección → artículo (máximo 3 clics a páginas clave).', 'URLs legibles y estables.', 'Breadcrumb con schema.', 'Menú principal alineado a money pages, no a orgullo interno.'] },
      { type: 'h2', text: 'Silo por categoría de negocio' },
      { type: 'p', text: 'Si vendes e-commerce, apps y SEO, cada silo tiene landing hub, subpáginas y contenido de apoyo que enlazan dentro del mismo silo (y cruzan solo cuando aporta al usuario).' },
      { type: 'h2', text: 'Enlazado interno contextual' },
      { type: 'ul', items: ['Anclas descriptivas (no “haz clic aquí”).', 'Artículos nuevos enlazan a hubs y viceversa en las primeras 48 h.', 'Links en sidebar/footer solo si son navegación real, no atasco.', 'Revisa 404 y enlaces huérfanos cada mes.'] },
      { type: 'h2', text: 'Plantilla de hub para servicios' },
      { type: 'p', text: '/servicios (hub) → /servicios/ecommerce (pillar) → casos y artículos relacionados enlazados con contexto. Ese patrón escala sin reescribir el menú cada trimestre.' },
      { type: 'p', text: 'Dibuja el tree en un sheet antes de tocar el CMS. Casi siempre descubres páginas que nadie necesita.' },
    ],
  },
  {
    slug: 'diseno-para-adultos-mayores',
    title: 'Diseño web accesible para adultos mayores',
    metaDescription:
      'Prácticas de accesibilidad web para mayores: tamaño de fuente, contraste, targets táctiles, formularios y lenguaje claro según WCAG.',
    category: 'diseno',
    tags: ['Accesibilidad', 'WCAG', 'Inclusión', 'UI'],
    excerpt:
      'Una parte enorme de tu tráfico tiene más de 55 años. Contraste, targets y formularios fáciles mejoran la experiencia para todos, no solo para ellos.',
    date: '2026-08-07',
    author: 'María Fernanda Ruiz',
    authorRole: 'Diseñadora de producto',
    readTime: 7,
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Persona mayor usando una tableta con interfaz sencilla',
    content: [
      { type: 'p', text: 'Diseñar para adultos mayores no es “agrandar todo”: es eliminar ambigüedad, respetar tiempos y dar opciones alternativas cuando algo falla.' },
      { type: 'h2', text: 'Tipografía y contraste' },
      { type: 'ul', items: ['Tamaño base 16–18px; interlineado 1.5–1.6.', 'Contraste mínimo AA: 4.5:1 texto normal, 3:1 texto grande.', 'Evitar texto justificado largo y párrafos de más de 75 caracteres en móvil.', 'Botones de zoom del navegador sin romper layout.'] },
      { type: 'h2', text: 'Targets y errores' },
      { type: 'ul', items: ['Área táctil ≥ 44×44 px y espacio entre acciones.', 'Labels visibles (no solo placeholder).', 'Errores en lenguaje humano: “Falta tu correo” no “required field”.', 'Mensajes de éxito y de error en regiones aria-live.'] },
      { type: 'h2', text: 'Lenguaje y tiempo' },
      { type: 'p', text: 'Oraciones cortas. Plazos explícitos. Ofrecer teléfono como alternativa al formulario. No auto-logout agresivo en flujos de compra o trámites.' },
      { type: 'h2', text: 'Cómo validar' },
      { type: 'ul', items: ['Prueba con zoom 200% y teclado solo.', 'Lighthouse Accessibility + revisión manual de flujos críticos.', 'Sesiones con usuarios reales mayores; el dinero está en la observación.'] },
      { type: 'p', text: 'Lo que ayudas a un usuario de 70 años suele ayudar también a quien navega en el metro con una mano.' },
    ],
  },
  {
    slug: 'erp-y-tu-tienda-online',
    title: 'Integrar ERP con tu tienda online: guía sin dolores',
    metaDescription:
      'Cómo conectar WooCommerce o Shopify con tu ERP: stock, pedidos, clientes y sincronización. Errores comunes y plan de integración por fases.',
    category: 'ecommerce',
    tags: ['ERP', 'Integraciones', 'Automatización', 'E-commerce'],
    excerpt:
      'Stock fantasma y pedidos a mano matan la operación. Fases claras para sincronizar catálogo, inventario y facturación con tu ERP.',
    date: '2026-08-05',
    author: 'Diego Herrera',
    authorRole: 'Lead e-commerce',
    readTime: 9,
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Almacén con estanterías organizadas representando inventario sincronizado',
    content: [
      { type: 'p', text: 'Cuando la tienda y el ERP no hablan, tu equipo se convierte en el middleware humano. La integración no tiene por qué ser un proyecto de un año: sélo en fases.' },
      { type: 'h2', text: 'Qué sincronizar primero' },
      { type: 'ul', items: ['Fase 1: catálogo y precios (o al menos SKU + stock mínimo).', 'Fase 2: pedidos de la tienda → ERP (estado de vuelta a la web).', 'Fase 3: clientes y facturación.', 'Fase 4: promociones, packs y lógica avanzada.'] },
      { type: 'h2', text: 'Patrones de integración' },
      { type: 'ul', items: ['Middleware iPaaS (Make, n8n, Celigo…) para ERP SaaS con webhooks.', 'API nativa o conector certificado del ERP.', 'Cola de eventos + reintentos: nunca confíes en un solo POST.', 'Idempotencia en pedidos para no duplicar.'] },
      { type: 'h2', text: 'Errores típicos' },
      { type: 'ul', items: ['Sync bidireccional de precio sin dueño claro (¿quién gana?).', 'Stock negativo por carreras de checkout.', 'Sin logs ni alertas cuando el job falla a las 3 a.m.', 'Migrar historial completo en el go-live en vez de por lotes.'] },
      { type: 'p', text: 'Define dueño de datos por campo (ERP manda en stock; la web manda en reseñas). Con eso escrito, la mitad de los conflictos de diseño desaparecen.' },
    ],
  },
  {
    slug: 'ai-en-productos-digitales',
    title: 'IA en productos digitales: usos que sí aportan valor',
    metaDescription:
      'Casos prácticos de IA en web y apps: búsqueda semántica, soporte, personalización y content ops. Cómo priorizar features de IA con ROI real.',
    category: 'saas',
    tags: ['IA', 'Producto digital', 'Automatización', 'Innovación'],
    excerpt:
      'Más allá del hype, la IA ayuda en soporte, búsqueda y generación asistida. Cómo elegir un caso de uso con métrica y evitar demos inútiles.',
    date: '2026-08-02',
    author: 'Carlos Mendoza',
    authorRole: 'Director de proyectos',
    readTime: 8,
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Visual abstracto de inteligencia artificial con luces neón',
    content: [
      { type: 'p', text: 'La pregunta útil no es “¿dónde ponemos IA?” sino “¿dónde perdemos horas o conversiones hoy?”. El ROI aparece cuando automatizas fricción repetitiva.' },
      { type: 'h2', text: 'Casos con retorno claro' },
      { type: 'ul', items: ['Asistente de soporte con base de conocimiento (reduce tickets Level 1).', 'Búsqueda semántica en catálogos grandes.', 'Resumen de reseñas y Q&A de producto.', 'Drafts de contenido y variantes de email para humanos que editan.', 'Clasificación y enrutado de leads entrantes.'] },
      { type: 'h2', text: 'Casos a evitar en fase 1' },
      { type: 'ul', items: ['Chat flotante sin handoff a humanos.', 'Generación masiva de textos SEO sin revisión (riesgo de marca y quality).', 'Features de “IA” que no tocan una métrica del negocio.'] },
      { type: 'h2', text: 'Métrica y guardrails' },
      { type: 'p', text: 'Define baseline (tiempo de respuesta, CSAT, tasa de auto-resolución) antes de lanzar. Añade disclaimer cuando hable la IA, logs de conversación y kill switch.' },
      { type: 'h2', text: 'Arquitectura mínima' },
      { type: 'ul', items: ['Retrieval sobre tu contenido (RAG) en vez de alucinar hechos.', 'Modelo barato para clasificación; caro solo cuando aporte.', 'Evaluación automática de respuestas en staging.', 'Privacidad: no envíes PII a APIs sin acuerdo.'] },
      { type: 'p', text: 'Empieza con un workflow acotado, mídelo un mes y decide escalar. La IA es un feature más, no una religión de producto.' },
    ],
  },
  {
    slug: 'imagenes-web-peso-y-umbral',
    title: 'Imágenes en la web: formatos, peso y buenas prácticas',
    metaDescription:
      'Guía de imágenes web 2026: AVIF/WebP, responsive srcset, lazy loading correcto y CDN. Menos peso, mejor LCP y UX.',
    category: 'web',
    tags: ['Imágenes', 'Rendimiento', 'AVIF', 'LCP'],
    excerpt:
      'Las imágenes suelen ser el mayor payload de una landing. Cómo servir el formato correcto, dimensiones exactas y prioridad de carga.',
    date: '2026-07-30',
    author: 'Andrés Ponce',
    authorRole: 'Tech lead móvil',
    readTime: 6,
    image: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Cámara y fotografías representando optimización de imágenes',
    content: [
      { type: 'p', text: 'Una hero de 4 MB arruina cualquier presupuesto de performance. El pipeline de imágenes correcto es de las victorias más rápidas en Core Web Vitals.' },
      { type: 'h2', text: 'Formatos' },
      { type: 'ul', items: ['AVIF: mejor compresión; buen soporte en 2026 con fallback.', 'WebP: estándar seguro para fotos.', 'PNG solo si necesitas transparencia fina; SVG para iconos.', 'JPEG de baja calidad solo como último fallback.'] },
      { type: 'h2', text: 'Responsive de verdad' },
      { type: 'p', text: 'Usa srcset + sizes según el layout (no sirve de nada tener 1600w si en móvil se renderiza a 400px). Genera 2–4 variantes por asset clave.' },
      { type: 'h2', text: 'Carga' },
      { type: 'ul', items: ['Hero: fetchpriority="high", sin lazy, dimensiones explícitas.', 'Resto: loading="lazy" + width/height o aspect-ratio.', 'Preload selectivo de la imagen LCP, no de todo el carrusel.', 'CDN con transform on-the-fly (o build-time si el stack es estático).'] },
      { type: 'h2', text: 'Alt y SEO de imagen' },
      { type: 'p', text: 'Alt descriptivo con contexto, filenames legibles y sitemap de imágenes si el tráfico de Google Images importa (moda, recetas, productos).' },
      { type: 'p', text: 'Auditiza con Coverage en DevTools: casi siempre hay 1–2 MB de imágenes “de adorno” listas para eliminar.' },
    ],
  },
  {
    slug: 'crm-para-negocios-pequenos',
    title: 'CRM para negocios pequeños: empezar sin abrumarse',
    metaDescription:
      'Cómo elegir e implementar un CRM pequeño: campos mínimos, pipeline, automatizaciones y conexión con web y email. Checklist de arranque.',
    category: 'marketing',
    tags: ['CRM', 'Ventas', 'Automatización', 'Pequeñas empresas'],
    excerpt:
      'Un CRM con 80 campos nadie llena es peor que una hoja de cálculo. Pipeline simple, datos de tu web y hábitos que el equipo sí mantiene.',
    date: '2026-07-27',
    author: 'Sofía Ramírez',
    authorRole: 'Growth marketer',
    readTime: 7,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Equipo revisando un pipeline de ventas en una pizarra',
    content: [
      { type: 'p', text: 'El mejor CRM es el que el equipo actualiza sin que el dueño lo persiga. Empieza con menos campos y más disciplina.' },
      { type: 'h2', text: 'Campos mínimos viables' },
      { type: 'ul', items: ['Empresa, contacto, email, teléfono.', 'Origen (web, referencia, ads).', 'Etapa del pipeline.', 'Última actividad y próximo paso con fecha.', 'Presupuesto estimado (si aplica).'] },
      { type: 'h2', text: 'Pipeline de 5 etapas' },
      { type: 'p', text: 'Nuevo → Calificado → Propuesta → Negociación → Ganado/Perdido. Motivos de pérdida con categorías: te darán datos de producto y de precio.' },
      { type: 'h2', text: 'Conecta la web primero' },
      { type: 'ul', items: ['Formulario de contacto y cotizador → CRM con UTM y página de origen.', 'Alerta al owner en minutos, no al día siguiente.', 'Secuencia de 2–3 emails automáticos mientras el lead es caliente.'] },
      { type: 'h2', text: 'Hábitos semanales' },
      { type: 'ul', items: ['Limpieza de leads sin actividad 30 días.', 'Revisión de pipeline de 15 minutos los lunes.', 'Reporte simple: leads, cierres, ticket promedio.'] },
      { type: 'p', text: 'Cuando el equipo pida campos nuevos, ya sabes que el CRM está vivo. Hasta entonces, resiste la tentación de “configurarlo todo” el primer día.' },
    ],
  },
  {
    slug: 'multiidioma-y-hreflang',
    title: 'Sitios multiidioma: hreflang, URLs y contenido real',
    metaDescription:
      'Implementa un sitio multiidioma sin problemas de SEO: etiquetas hreflang, estrategia de URLs, traducción y contenido localizado de verdad.',
    category: 'seo',
    tags: ['Multiidioma', 'hreflang', 'SEO internacional', 'Traducción'],
    excerpt:
      'Traducir no es localizar. Cómo estructurar idiomas, evitar contenido duplicado y darle a Google la señal hreflang correcta.',
    date: '2026-07-24',
    author: 'Laura Gómez',
    authorRole: 'Especialista SEO técnico',
    readTime: 8,
    image: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Globo terráqueo y banderas representando idiomas internacionales',
    content: [
      { type: 'p', text: 'Un sitio multiidioma mal montado genera contenido duplicado, tráfico mezclado y conversiones bajas. La base es arquitectura + hreflang + calidad de texto.' },
      { type: 'h2', text: 'Estrategia de URLs' },
      { type: 'ul', items: ['Subdirectorio (/es/, /en/) suele ser la mejor relación coste–SEO para dominios nuevos.', 'Subdominio si equipos/marketing muy separados.', 'ccTLD (.es, .mx) si el negocio es fuertemente por país y el presupuesto lo permite.'] },
      { type: 'h2', text: 'hreflang que funciona' },
      { type: 'ul', items: ['Bidireccional y con x-default.', 'Cada URL declara todos los idiomas, incluida la propia.', 'Sitemap alternates o head HTML; no solo uno de los dos si el sitio es grande.', 'Sin códigos de país inválidos (es-ES ≠ es) salvo que sea correcto.'] },
      { type: 'h2', text: 'Contenido localizado, no traducido a medias' },
      { type: 'p', text: 'Unidades, moneda, ejemplos de casos, dirección de negocio y tono deben sentirse locales. Un MTPE (máquina + revisión humana) funciona en muchos contextos; el literalismo no.' },
      { type: 'h2', text: 'Errores fatales' },
      { type: 'ul', items: ['Redirigir por IP sin opción de elegir idioma.', 'Geobloqueo agresivo que impide Googlebot rastrear.', 'hreflang apuntando a redirecciones 3xx.', 'Traducir solo el menú y dejar el artículo en un idioma.'] },
      { type: 'p', text: 'Valida en Search Console (Rendimiento filtrado por URL) y con un checker de hreflang tras cada release de plantilla.' },
    ],
  },
  {
    slug: 'onboarding-de-clientes-en-agencias',
    title: 'Onboarding de clientes en agencias: el primer mes',
    metaDescription:
      'Proceso de onboarding para agencias: kick-off, accesos, expectativas, calendario y entregables del primer mes para reducir churn y rework.',
    category: 'saas',
    tags: ['Agencia', 'Onboarding', 'Gestión de clientes', 'Procesos'],
    excerpt:
      'El 50% de la satisfacción del proyecto se juega en las primeras dos semanas. Plantilla de kick-off, accesos y rituales que evitan sorpresas.',
    date: '2026-07-20',
    author: 'Carlos Mendoza',
    authorRole: 'Director de proyectos',
    readTime: 7,
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Reunión de equipo de agencia en una oficina moderna',
    content: [
      { type: 'p', text: 'Los proyectos se pierden en expectativas no dichas. Un onboarding estructurado protege margen, plazo y relación con el cliente.' },
      { type: 'h2', text: 'Días 1–3: kick-off y accesos' },
      { type: 'ul', items: ['Sesión con objetivos, audiencias y definición de “listo”.', 'Canal único de comunicación + SLA de respuesta.', 'Checklist de accesos: hosting, DNS, Analytics, Search Console, CMS, diseños.', 'Documento de decisiones (DOD) compartido.'] },
      { type: 'h2', text: 'Semana 1: mapa y riesgos' },
      { type: 'ul', items: ['Inventory de contenido y dependencias del cliente.', 'Riesgos listados con dueño (cliente vs agencia).', 'Calendario de hitos con fechas de revisión del cliente.'] },
      { type: 'h2', text: 'Semanas 2–4: cadencia' },
      { type: 'ul', items: ['Demo semanal corta (no email de 800 palabras).', 'Una sola persona del lado del cliente con poder de decisión.', 'Change requests por escrito con impacto en fecha/presupuesto.'] },
      { type: 'h2', text: 'Salida del mes 1' },
      { type: 'p', text: 'Si al cierre de la semana 4 no hay prototipo/landing visible o plan firmado de fases, re/calibra alcance ya. El onboarding no termina con la firma del contrato; termina cuando ambos ven el camino.' },
      { type: 'p', text: 'Plantilla práctica: folder con README, accesos, calendario y glosario. Deja de reenviar hilos eternos de correo.' },
    ],
  },
  {
    slug: 'formularios-que-el-usuario-completa',
    title: 'Formularios que el usuario sí completa',
    metaDescription:
      'Optimiza formularios web: campos, validación, autocompletado, seguridad antispam y patrones mobile-first que suben la tasa de envío.',
    category: 'diseno',
    tags: ['Formularios', 'UX', 'Conversión', 'Validación'],
    excerpt:
      'Cada campo es una barrera. Cómo validar sin castigar, usar autocomplete y diseñar formularios que se terminan en el móvil.',
    date: '2026-07-16',
    author: 'María Fernanda Ruiz',
    authorRole: 'Diseñadora de producto',
    readTime: 6,
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Persona llenando un formulario en un dispositivo móvil',
    content: [
      { type: 'p', text: 'Los formularios son el pasillo angosto de la tienda: todo el tráfico depende de que quepan por ahí sin estancarse.' },
      { type: 'h2', text: 'Menos campos, más contexto' },
      { type: 'ul', items: ['Pide solo lo necesario para el siguiente paso humano.', 'Explica por qué pides teléfono o presupuesto.', 'Divide en pasos si son +6 campos (wizard con progreso).'] },
      { type: 'h2', text: 'Validación amable' },
      { type: 'ul', items: ['Validar al blur o al intentar enviar, no a cada tecla.', 'Mensajes específicos junto al campo.', 'No borrar lo que el usuario ya escribió en error de servidor.', 'type y autocomplete correctos (name, email, tel, organization).'] },
      { type: 'h2', text: 'Mobile first' },
      { type: 'ul', items: ['teclado correcto (email, numérico).', 'Botón de enviar visible sin scroll eterno.', 'Targets grandes y contraste suficiente.', 'Evitar datepickers rotos: ofrecer ayudas o formatos simples.'] },
      { type: 'h2', text: 'Spam sin castigar al humano' },
      { type: 'p', text: 'Honeypot o Turnstile invisible suelen bastar. CAPTCHAs de puzzles elevados matan conversión en leads de alto valor.' },
      { type: 'p', text: 'Mide drop-off por campo con herramientas de form analytics: el campo “empresa (opcional)” a veces es el asesino silencioso.' },
    ],
  },
  {
    slug: 'analytics-sin-ruido',
    title: 'Analytics sin ruido: 12 métricas que importan',
    metaDescription:
      'Deja de mirar vanity metrics. 12 KPIs de web y producto (conversión, cohortes, LTV) con umbrales y cadencia de revisión.',
    category: 'marketing',
    tags: ['Analytics', 'KPI', 'GA4', 'Medición'],
    excerpt:
      'Visitas sin contexto no ayudan a decidir. Un panel corto con conversiones, calidad de tráfico y salud del embudo basta para la mayoría.',
    date: '2026-07-12',
    author: 'Sofía Ramírez',
    authorRole: 'Growth marketer',
    readTime: 7,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
    imageAlt: 'Panel de analítica con gráficos de líneas y barras',
    content: [
      { type: 'p', text: 'Los dashboards con 40 tarjetas producen parálisis. Elige métricas que cambien decisiones de producto, marketing o ventas.' },
      { type: 'h2', text: 'Adquisición (4)' },
      { type: 'ul', items: ['Sesiones orgánicas vs paid por landing.', 'Tasa de conversión por canal (lead o compra).', 'CAC por canal.', 'Share de marca vs no brand en búsqueda.'] },
      { type: 'h2', text: 'Conversión y producto (4)' },
      { type: 'ul', items: ['Tasa de conversión global y por dispositivo.', 'Top exit pages en embudo.', 'Activación (usuarios que llegan al “aha”).', 'Tiempo mediano hasta la primera conversión.'] },
      { type: 'h2', text: 'Salud y negocio (4)' },
      { type: 'ul', items: ['Core Web Vitals de campo.', 'Leads calificados / tasa de cierre.', 'LTV o pedidos repetidos si hay recurrencia.', 'Churn o abandono de carrito (según modelo).'] },
      { type: 'h2', text: 'Cadencia' },
      { type: 'p', text: 'Diario: conversiones y alertas. Semanal: canales y embudos. Mensual: cohortes, LTV y experimentos. Trimestral: revisar si las métricas siguen alineadas al negocio.' },
      { type: 'p', text: 'Si una métrica no tiene dueño ni acción asociada, bórrala del panel hoy.' },
    ],
  },
];

export function getPostBySlug(slug) {
  return posts.find((p) => p.slug === slug);
}

export function getCategoryLabel(key) {
  return categories.find((c) => c.key === key)?.label ?? key;
}
